version: '3.5'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8080:8080
    environment:
      APP_ROOT: /opt/app-root/public
      LISTEN_PORT: 8080
      PHP_HOST: phpfpm
      PHP_FPM_PORT: 9000
    volumes:
      - "./api:/opt/app-root"

  phpfpm:
    build:
      context: ./docker/php-fpm
      target: dev
    working_dir: /opt/app-root/
    environment:
      APP_DIR: /opt/app-root
      LISTEN_PORT: 9000
      LISTEN_HOST: 0.0.0.0
    volumes:
      - "./api:/opt/app-root"
