version: '3.5'

services:

  reverse-proxy:
    image: traefik:v2.5
    networks:
      default:
        aliases:
          - kvasir.local # for internal https communication to the api; if required
    ports:
      - "7777:7777"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.yaml:/traefik.yaml
      - ./docker/traefik/traefik-dynamic-config.yaml:/traefik-dynamic-config.yaml
      - ./certs:/certs

  nginx:
    build:
      context: ./docker/images/nginx
    environment:
      APP_ROOT: ${APP_ROOT}/public
      LISTEN_PORT: ${NGINX_PORT}
      PHP_HOST: phpfpm
      PHP_FPM_PORT: ${PHPFPM_PORT}
    volumes:
      - "./api:${APP_ROOT}"
    labels:
      - "traefik.http.routers.nginx.rule=Host(`kvasir.local`)"
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=${NGINX_PORT}"
      - "traefik.http.routers.nginx.tls=true"

  phpfpm:
    build:
      context: ./docker/images/php-fpm
      target: dev
    working_dir: ${APP_ROOT}/
    environment:
      APP_DIR: ${APP_ROOT}
      LISTEN_PORT: ${PHPFPM_PORT}
      LISTEN_HOST: 0.0.0.0
      COMPOSER_AUTH: "{\"github-oauth\": {\"github.com\": \"${GITHUB_OAUTH_TOKEN}\"}}"
      # We use this until php-cs-fixer supports symfony 6
      PHP_CS_FIXER_IGNORE_ENV: true
    volumes:
      - "./api:${APP_ROOT}"
